# Minimal makefile for Sphinx documentation
#
GIT_ROOT	:= $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST)))/..)
VENV_ROOT	:= $(GIT_ROOT)/.venv
VENV		?= $(VENV_ROOT)

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = $(VENV)/bin/sphinx-build
SPHINXPROJ    = HTTPretty
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
